
# countries arrange by continent, then alphabetical order; continent-codes are below
countries = ["Antigua and Barbuda",	"Australia",	"Bahamas",	"Bahrain",	"Barbados",	"Cape Verde",	"Comoros",	"Cuba",	"Cyprus",	"Dominica",	"Fiji",	"Grenada",	"Iceland",	"Jamaica",	"Japan",	"Kiribati",	"Madagascar",	"Maldives",	"Malta",	"Marshall Islands",	"Mauritius",	"Micronesia",	"Nauru",	"New Zealand",	"Palau",	"Philippines",	"Saint Kitts and Nevis ",	"Saint Lucia",	"Saint Vincent and the Grenadines",	"Samoa",	"São Tomé and Príncipe",	"Seychelles",	"Singapore",	"Solomon Islands",	"Taiwan",	"Tonga",	"Trinidad and Tobago",	"Tuvalu",	"Vanuatu",	"Afghanistan",	"Azerbaijan",	"Bangladesh",	"Bhutan",	"Brunei",	"Cambodia",	"China",	"East Timor",	"India",	"Indonesia",	"Iran",	"Iraq",	"Israel",	"Jordan",	"Kazakhstan",	"Kuwait",	"Kyrgyzstan",	"Laos",	"Lebanon",	"Malaysia",	"Mongolia",	"Myanmar",	"Nepal",	"North Korea",	"Oman",	"Pakistan",	"Papua New Guinea",	"Qatar",	"Saudi Arabia",	"South Korea",	"Sri Lanka",	"Syria",	"Tajikistan",	"Thailand",	"Turkey",	"Turkmenistan",	"United Arab Emirates",	"Uzbekistan",	"Vietnam",	"Yemen",	"Albania",	"Andorra",	"Armenia",	"Austria",	"Belarus",	"Belgium",	"Bosnia and Herzegovina",	"Bulgaria",	"Croatia",	"Czech Republic",	"Denmark",	"Estonia",	"Finland",	"France",	"Georgia",	"Germany",	"Greece",	"Hungary",	"Ireland",	"Italy",	"Kosovo",	"Latvia",	"Liechtenstein",	"Lithuania",	"Luxembourg",	"Macedonia",	"Moldova",	"Monaco",	"Montenegro",	"Netherlands",	"Norway",	"Poland",	"Portugal",	"Romania",	"Russia",	"San Marino",	"Serbia",	"Slovakia",	"Slovenia",	"Spain",	"Sweden",	"Switzerland",	"Ukraine",	"United Kingdom",	"Vatican City",	"Algeria",	"Angola",	"Benin",	"Botswana",	"Burkina Faso",	"Burundi",	"Cameroon",	"Central African Republic",	"Chad",	"Democratic Republic of the Congo",	"Djibouti",	"Egypt",	"Equatorial Guinea",	"Eritrea",	"eSwatini",	"Ethiopia",	"Gabon",	"Gambia",	"Ghana",	"Guinea",	"Guinea-Bissau",	"Ivory Coast",	"Kenya",	"Lesotho",	"Liberia",	"Libya",	"Malawi",	"Mali",	"Mauritania",	"Morocco",	"Mozambique",	"Namibia",	"Niger",	"Nigeria",	"Republic of the Congo",	"Rwanda",	"Senegal",	"Sierra Leone",	"Somalia",	"South Africa",	"South Sudan",	"Sudan",	"Tanzania",	"Togo",	"Tunisia",	"Uganda",	"Zambia",	"Zimbabwe",	"Argentina",	"Bolivia",	"Brazil",	"Chile",	"Colombia",	"Ecuador",	"Guyana",	"Paraguay",	"Peru",	"Suriname",	"Uruguay",	"Venezuela",	"Belize",	"Costa Rica",	"El Salvador",	"Guatemala",	"Honduras",	"Mexico",	"Nicaragua",	"Panama",	"Canada",	"United States",	"Dominican Republic",	"Haiti"]

# continent-codes; 0 = island, 1 = asia, 2 = europe, 3 = africa, 6 = south america, 7 = central america, 8 = north america, 11 = haiti/dom-rep
codes = [0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	7,	7,	7,	7,	7,	7,	7,	7,	8,	8,	11,	11]

# bordering countries; order corresponds to the countries list i.e. first entry shows borders of Antigua and Barbuda, etc
borders = [
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
[],
["China","Iran","Pakistan","Tajikistan","Turkmenistan","Uzbekistan"],
["Armenia","Georgia","Iran","Russia","Turkey"],
["Myanmar","India"],
["China","India"],
["Malaysia"],
["Laos","Thailand","Vietnam"],
["Afghanistan","Bhutan","Myanmar","India","Kazakhstan","Kyrgyzstan","Laos","Mongolia","Nepal","North Korea","Pakistan","Russia","Tajikistan","Vietnam"],
["Indonesia"],
["Bangladesh","Bhutan","Myanmar","China","Nepal","Pakistan","Sri Lanka"],
["East Timor","Malaysia","Papua New Guinea"],
["Afghanistan","Armenia","Azerbaijan","Iraq","Pakistan","Turkey","Turkmenistan"],
["Iran","Jordan","Kuwait","Saudi Arabia","Syria","Turkey"],
["Egypt","Jordan","Lebanon","Syria"],
["Iraq","Israel","Saudi Arabia","Syria"],
["China","Kyrgyzstan","Russia","Turkmenistan","Uzbekistan"],
["Iraq","Saudi Arabia"],
["China","Kazakhstan","Tajikistan","Uzbekistan"],
["Myanmar","Cambodia","China","Thailand","Vietnam"],
["Israel","Syria"],
["Brunei","Indonesia","Thailand"],
["China","Russia"],
["Bangladesh","China","India","Laos","Thailand"],
["China","India"],
["China","Russia","South Korea"],
["Saudi Arabia","United Arab Emirates","Yemen"],
["Afghanistan","China","India","Iran"],
["Indonesia"],
["Saudi Arabia","United Arab Emirates"],
["Iraq","Jordan","Kuwait","Oman","Qatar","United Arab Emirates","Yemen"],
["North Korea"],
["India"],
["Iraq","Israel","Jordan","Lebanon","Turkey"],
["Afghanistan","China","Kyrgyzstan","Uzbekistan"],
["Myanmar","Cambodia","Laos","Malaysia"],
["Armenia","Azerbaijan","Bulgaria","Georgia","Greece","Iran","Iraq","Syria"],
["Afghanistan","Iran","Kazakhstan","Uzbekistan"],
["Oman","Qatar","Saudi Arabia"],
["Afghanistan","Kazakhstan","Kyrgyzstan","Tajikistan","Turkmenistan"],
["Cambodia","China","Laos"],
["Oman","Saudi Arabia"],
["Greece","Kosovo","Macedonia","Montenegro"],
["France","Spain"],
["Azerbaijan","Georgia","Iran","Turkey"],
["Czech Republic","Germany","Hungary","Italy","Liechtenstein","Slovakia","Slovenia","Switzerland"],
["Latvia","Lithuania","Poland","Russia","Ukraine"],
["France","Germany","Luxembourg","Netherlands"],
["Croatia","Montenegro","Serbia"],
["Greece","Macedonia","Romania","Serbia","Turkey"],
["Bosnia and Herzegovina","Hungary","Montenegro","Serbia","Slovenia"],
["Austria","Germany","Poland","Slovakia"],
["Germany"],
["Latvia","Russia"],
["Norway","Russia","Sweden"],
["Andorra","Belgium","Brazil","Germany","Italy","Luxembourg","Monaco","Netherlands","Spain","Suriname","Switzerland"],
["Armenia","Azerbaijan","Russia","Turkey"],
["Austria","Belgium","Czech Republic","Denmark","France","Luxembourg","Netherlands","Poland","Switzerland"],
["Albania","Bulgaria","Macedonia","Turkey"],
["Austria","Croatia","Romania","Serbia","Slovakia","Slovenia","Ukraine"],
["United Kingdom"],
["Austria","France","San Marino","Slovenia","Switzerland","Vatican City"],
["Albania","Macedonia","Montenegro","Serbia"],
["Belarus","Estonia","Lithuania","Russia"],
["Austria","Switzerland"],
["Belarus","Latvia","Poland","Russia"],
["Belgium","France","Germany"],
["Albania","Bulgaria","Greece","Kosovo","Serbia"],
["Romania","Ukraine"],
["France"],
["Albania","Bosnia and Herzegovina","Croatia","Kosovo","Serbia"],
["Belgium","France","Germany"],
["Finland","Russia","Sweden"],
["Belarus","Czech Republic","Germany","Lithuania","Russia","Slovakia","Ukraine"],
["Spain"],
["Bulgaria","Hungary","Moldova","Serbia","Ukraine"],
["Azerbaijan","Belarus","China","Estonia","Finland","Georgia","Kazakhstan","Latvia","Lithuania","Mongolia","North Korea","Norway","Poland","Ukraine"],
["Italy"],
["Bosnia and Herzegovina","Bulgaria","Croatia","Hungary","Kosovo","Macedonia","Montenegro","Romania"],
["Austria","Czech Republic","Hungary","Poland","Ukraine"],
["Austria","Croatia","Hungary","Italy"],
["Andorra","France","Morocco","Portugal","United Kingdom"],
["Finland","Norway"],
["Austria","France","Germany","Italy","Liechtenstein"],
["Belarus","Hungary","Moldova","Poland","Romania","Russia","Slovakia"],
["Ireland","Spain"],
["Italy"],
["Libya","Mali","Mauritania","Morocco","Niger","Tunisia"],
["Democratic Republic of the Congo","Namibia","Republic of the Congo","Zambia"],
["Burkina Faso","Niger","Nigeria","Togo"],
["Namibia","South Africa","Zambia","Zimbabwe"],
["Benin","Ivory Coast","Ghana","Mali","Niger","Togo"],
["Democratic Republic of the Congo","Rwanda","Tanzania"],
["Central African Republic","Chad","Equatorial Guinea","Gabon","Nigeria","Republic of the Congo"],
["Cameroon","Chad","Democratic Republic of the Congo","Republic of the Congo","South Sudan","Sudan"],
["Cameroon","Central African Republic","Libya","Niger","Nigeria","Sudan"],
["Angola","Burundi","Central African Republic","Republic of the Congo","Rwanda","South Sudan","Tanzania","Uganda","Zambia"],
["Eritrea","Ethiopia","Somalia"],
["Israel","Libya","Sudan"],
["Cameroon","Gabon"],
["Djibouti","Ethiopia","Sudan"],
["Mozambique","South Africa"],
["Djibouti","Eritrea","Kenya","Somalia","South Sudan","Sudan"],
["Cameroon","Equatorial Guinea","Republic of the Congo"],
["Senegal"],
["Burkina Faso","Ivory Coast","Togo"],
["Ivory Coast", "Guinea-Bissau","Liberia","Mali","Senegal","Sierra Leone"],
["Guinea","Senegal"],
["Burkina Faso","Ghana","Guinea","Liberia","Mali"],
["Ethiopia","Somalia","South Sudan","Tanzania","Uganda"],
["South Africa"],
["Ivory Coast","Guinea","Sierra Leone"],
["Algeria","Chad","Egypt","Niger","Sudan","Tunisia"],
["Mozambique","Tanzania","Zambia"],
["Algeria","Burkina Faso","Ivory Coast","Guinea","Mauritania","Niger","Senegal"],
["Algeria","Mali","Morocco","Senegal"],
["Algeria","Mauritania","Spain"],
["Malawi","South Africa","eSwatini","Tanzania","Zambia","Zimbabwe"],
["Angola","Botswana","South Africa","Zambia"],
["Algeria","Benin","Burkina Faso","Chad","Libya","Mali","Nigeria"],
["Benin","Cameroon","Chad","Niger"],
["Angola","Cameroon","Central African Republic","Democratic Republic of the Congo","Gabon"],
["Burundi","Democratic Republic of the Congo","Tanzania","Uganda"],
["Gambia","Guinea","Guinea-Bissau","Mali","Mauritania"],
["Guinea","Liberia"],
["Djibouti","Ethiopia","Kenya"],
["Botswana","Lesotho","Mozambique","Namibia","eSwatini","Zimbabwe"],
["Central African Republic","Democratic Republic of the Congo","Ethiopia","Kenya","Sudan","Uganda"],
["Central African Republic","Chad","Egypt","Eritrea","Ethiopia","Libya","South Sudan"],
["Burundi","Democratic Republic of the Congo","Kenya","Malawi","Mozambique","Rwanda","Uganda","Zambia"],
["Benin","Burkina Faso","Ghana"],
["Algeria","Libya"],
["Democratic Republic of the Congo","Kenya","Rwanda","South Sudan","Tanzania"],
["Angola","Botswana","Democratic Republic of the Congo","Malawi","Mozambique","Namibia","Tanzania","Zimbabwe"],
["Botswana","Mozambique","South Africa","Zambia"],
["Bolivia","Brazil","Chile","Paraguay","Uruguay"],
["Argentina","Brazil","Chile","Paraguay","Peru"],
["Argentina","Bolivia","Colombia","France","Guyana","Paraguay","Peru","Suriname","Uruguay","Venezuela"],
["Argentina","Bolivia","Peru"],
["Brazil","Ecuador","Panama","Peru","Venezuela"],
["Colombia","Peru"],
["Brazil","Suriname","Venezuela"],
["Argentina","Bolivia","Brazil"],
["Bolivia","Brazil","Chile","Colombia","Ecuador"],
["Brazil","France","Guyana"],
["Argentina","Brazil"],
["Brazil","Colombia","Guyana"],
["Guatemala","Mexico"],
["Nicaragua","Panama"],
["Guatemala","Honduras"],
["Belize","El Salvador","Honduras","Mexico"],
["El Salvador","Guatemala","Nicaragua"],
["Belize","Guatemala","United States"],
["Costa Rica","Honduras"],
["Colombia","Costa Rica"],
["United States"],
["Canada","Mexico"],
["Haiti"],
["Dominican Republic"]
]